#def
import java.util.*;
#enddef

Vector<String> getSongsList()[10.102.42.169]
Vector<String> getIPList()[10.102.42.169]
int Register(Vector <String> songNames, String ip)[10.102.42.169]
Vector<Byte>getSong (String SongName)[10.102.42.169]
Vector<Byte>getSonginParts(String SongName, Integer offset, Integer chunksize)[10.102.42.169]
